### ISSUE TITLE
Name and Description section can get out of sync with AccName due to step references

### ISSUE THREAD

**Issue by joanmarie** [w3c/svg-aam#16]
The [Name and Description](https://w3c.github.io/svg-aam/#mapping_additional_nd) section currently has phrases like:

> Replace step 2D with the following

and 

> In step 2F, modify step iii by replacing

The thing is, the AccName spec might add steps, change the order of the steps, or modify the language within a step. Should this occur, the SVG-AAM might get out of sync with AccName.

Aside: The non-normative note at the bottom is helpful. Maybe it could serve as the basis for a normative section?

**Comment by cookiecrook** [comment]
Overcome by #31
