### ISSUE TITLE
Add Ian Pouncey as new co-editor

### ISSUE THREAD

**Issue by AmeliaBR** [w3c/svg-aam#4]
If he is still interested, of course: @IanPouncey, we'll need your commitment as well as a WG resolution.

At the same time, mark @richschwer as a former editor.

**Comment by IanPouncey** [comment]
I am interested, have time available from my employer, and approval from my AC rep @LJWatson. There was a general agreement during our discussions at TPAC 2017, so this should just require formalising.

**Comment by AmeliaBR** [comment]
Resolved: Ian Pouncey is an editor on SVG-AAM (SVG WG teleconference 5 February 2018)

**Comment by AmeliaBR** [comment]
(reopen pending edits)

**Comment by AmeliaBR** [comment]
Closed by e6155d6b104a7c9ed205183339229a5f81f32b6b

(Just need to figure out how to trigger the Travis build to update the Editor's Draft!)
